language: php

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  include:
    - php: 5.4
      dist: trusty
    - php: 5.5
      dist: trusty
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3
      env: PHPSTAN=1
    - php: 7.4

before_script:
  - travis_retry composer install --prefer-source --quiet --no-interaction
  - if [[ $PHPSTAN = 1 ]]; then composer require --dev phpstan/phpstan:^0.12; fi

script:
  - vendor/bin/phpunit
  - composer lint
  - if [[ $PHPSTAN = 1 ]]; then vendor/bin/phpstan analyse -c phpstan.neon -l 4 src tests; fi
